### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by fri-it2** [perfsonar/ansible-role-perfsonar-archive#1]
Hello!
In https://github.com/perfsonar/ansible-role-perfsonar-archive/blob/master/tasks/main.yml is variable name `perfsonar_archiver_auth_list`, in all other files(https://github.com/perfsonar/ansible-role-perfsonar-archive/blob/master/defaults/main.yml) is variable name defined as `perfsonar_archive_auth_list`.
 Is this syntax error?
Best regards,
Tadeja

**Comment by epcjr** [comment]
This was a syntax error and has been fixed now.  Thank you!

Thanks,

-Ed
